INSERT INTO etudiant VALUES ("melody.ballouard@etu.utc.fr", "Ballouard", "Melody", "GP");
INSERT INTO uv (nom) VALUES ("AV01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RB118") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "VENDREDI", "RB118", 1, "Cours", "AV01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "13:00", "VENDREDI", "RB118");
INSERT INTO uv (nom) VALUES ("AV01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RB123") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "RB123", 2, "TD", "AV01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "08:00", "VENDREDI", "RB123");
INSERT INTO uv (nom) VALUES ("LG42") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC203") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FC203", 2, "TD", "LG42") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "10:15", "JEUDI", "FC203");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA317", 2, "Cours", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "08:00", "JEUDI", "FA317");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FB100", 2, "TD", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "10:15", "VENDREDI", "FB100");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "10:15", "LUNDI", "J210A");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA201", 2, "Cours", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "10:15", "MERCREDI", "FA201");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB215") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "VENDREDI", "FB215", 2, "TD", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("melody.ballouard@etu.utc.fr", "14:15", "VENDREDI", "FB215");
INSERT INTO etudiant VALUES ("david.konam@etu.utc.fr", "Konam", "David", "GSU");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA104", 2, "Cours", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "16:30", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB113") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FB113", 3, "TD", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "16:30", "MARDI", "FB113");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA205") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA205", 1, "Cours", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "13:00", "MARDI", "FA205");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB214") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "LUNDI", "FB214", 2, "TD", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "14:15", "LUNDI", "FB214");
INSERT INTO uv (nom) VALUES ("LG60") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA414") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA414", 2, "TD", "LG60") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "10:15", "LUNDI", "FA414");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "08:00", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "VENDREDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "13:15", "VENDREDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("david.konam@etu.utc.fr", "16:30", "MERCREDI", "J210A");
INSERT INTO etudiant VALUES ("benjamin.rivière@etu.utc.fr", "Rivière", "Benjamin", "GM");
INSERT INTO uv (nom) VALUES ("EI03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RN104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("18:45", "LUNDI", "RN104", 1, "Cours", "EI03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "18:45", "LUNDI", "RN104");
INSERT INTO uv (nom) VALUES ("EI03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RN104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:15", "SAMEDI", "RN104", 4, "TD", "EI03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "08:15", "SAMEDI", "RN104");
INSERT INTO uv (nom) VALUES ("GE36") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "LUNDI", "FA108", 1, "Cours", "GE36") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "09:00", "LUNDI", "FA108");
INSERT INTO uv (nom) VALUES ("GE36") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA307") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA307", 2, "TD", "GE36") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "08:00", "VENDREDI", "FA307");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA317", 2, "Cours", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "08:00", "JEUDI", "FA317");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FB100", 2, "TD", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "10:15", "JEUDI", "FB100");
INSERT INTO uv (nom) VALUES ("RO03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA100", 2, "Cours", "RO03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "16:30", "LUNDI", "FA100");
INSERT INTO uv (nom) VALUES ("RO03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MARDI", "FA516", 2, "TD", "RO03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "10:15", "MARDI", "FA516");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "16:30", "MARDI", "FA506");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA201", 2, "Cours", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "10:15", "MERCREDI", "FA201");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA509", 2, "TD", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("benjamin.rivière@etu.utc.fr", "08:00", "MERCREDI", "FA509");
INSERT INTO etudiant VALUES ("clément.passot@etu.utc.fr", "Passot", "Clément", "GI");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA104", 2, "Cours", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "16:30", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB113") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FB113", 3, "TD", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "16:30", "MARDI", "FB113");
INSERT INTO uv (nom) VALUES ("LG32") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA410") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "LUNDI", "FA410", 2, "TD", "LG32") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "08:00", "LUNDI", "FA410");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "08:00", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("NF28") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA200", 2, "Cours", "NF28") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "10:15", "LUNDI", "FA200");
INSERT INTO uv (nom) VALUES ("NF28") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO227") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "LUNDI", "RO227", 3, "TD", "NF28") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "13:00", "LUNDI", "RO227");
INSERT INTO uv (nom) VALUES ("SP01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("HSASP") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MARDI", "HSASP", 2, "Cours", "SP01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "10:15", "MARDI", "HSASP");
INSERT INTO uv (nom) VALUES ("SP01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("HSASP") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "HSASP", 2, "TD", "SP01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "14:15", "MARDI", "HSASP");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "VENDREDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "13:15", "VENDREDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("clément.passot@etu.utc.fr", "16:30", "MERCREDI", "J210A");
INSERT INTO etudiant VALUES ("thanh-thao.truong@etu.utc.fr", "Truong", "Thanh-Thao", "GB");
INSERT INTO uv (nom) VALUES ("GE15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA201", 1, "Cours", "GE15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "13:00", "MARDI", "FA201");
INSERT INTO uv (nom) VALUES ("GE15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA616") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA616", 2, "TD", "GE15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "14:15", "MARDI", "FA616");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA317", 2, "Cours", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "08:00", "JEUDI", "FA317");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FB100", 2, "TD", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "10:15", "VENDREDI", "FB100");
INSERT INTO uv (nom) VALUES ("SI14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC114") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MARDI", "FC114", 2, "TD", "SI14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "08:00", "MARDI", "FC114");
INSERT INTO uv (nom) VALUES ("SI14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC114") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "VENDREDI", "FC114", 1, "TP", "SI14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "09:00", "VENDREDI", "FC114");
INSERT INTO uv (nom) VALUES ("SR02") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA201", 2, "Cours", "SR02") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "10:15", "LUNDI", "FA201");
INSERT INTO uv (nom) VALUES ("SR02") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "VENDREDI", "FA506", 2, "TD", "SR02") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "16:30", "VENDREDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "16:30", "LUNDI", "FA506");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA201", 2, "Cours", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "10:15", "MERCREDI", "FA201");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB217") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FB217", 2, "TD", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("thanh-thao.truong@etu.utc.fr", "10:15", "JEUDI", "FB217");
INSERT INTO etudiant VALUES ("alexis.dupont@etu.utc.fr", "Dupont", "Alexis", "GB");
INSERT INTO uv (nom) VALUES ("IC06") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA204") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("15:15", "MERCREDI", "FA204", 1, "Cours", "IC06") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "15:15", "MERCREDI", "FA204");
INSERT INTO uv (nom) VALUES ("IC06") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RB123") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "RB123", 2, "TD", "IC06") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "14:15", "MARDI", "RB123");
INSERT INTO uv (nom) VALUES ("MI11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA202", 2, "Cours", "MI11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "10:15", "VENDREDI", "FA202");
INSERT INTO uv (nom) VALUES ("MI11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J207A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "J207A", 3, "TP", "MI11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "16:30", "LUNDI", "J207A");
INSERT INTO uv (nom) VALUES ("MI12") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:30", "JEUDI", "FA202", 1, "Cours", "MI12") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "08:30", "JEUDI", "FA202");
INSERT INTO uv (nom) VALUES ("MI12") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RJ216") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "RJ216", 4, "TD", "MI12") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "08:00", "MERCREDI", "RJ216");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "10:15", "LUNDI", "J210A");
INSERT INTO uv (nom) VALUES ("SY15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA202", 2, "Cours", "SY15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "10:15", "JEUDI", "FA202");
INSERT INTO uv (nom) VALUES ("SY15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "JEUDI", "FA516", 2, "TD", "SY15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "16:30", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("SY26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "LUNDI", "FA202", 2, "Cours", "SY26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "08:00", "LUNDI", "FA202");
INSERT INTO uv (nom) VALUES ("SY26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB215") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FB215", 2, "TD", "SY26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "16:30", "MARDI", "FB215");
INSERT INTO uv (nom) VALUES ("SY26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB215") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "LUNDI", "FB215", 2, "TP", "SY26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("alexis.dupont@etu.utc.fr", "14:15", "LUNDI", "FB215");
INSERT INTO etudiant VALUES ("jo.colina@etu.utc.fr", "Colina", "Jo", "GM");
INSERT INTO uv (nom) VALUES ("GE15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA201", 1, "Cours", "GE15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "13:00", "MARDI", "FA201");
INSERT INTO uv (nom) VALUES ("GE15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA616") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA616", 2, "TD", "GE15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "14:15", "MARDI", "FA616");
INSERT INTO uv (nom) VALUES ("GE39") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO229") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "LUNDI", "RO229", 1, "Cours", "GE39") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "13:00", "LUNDI", "RO229");
INSERT INTO uv (nom) VALUES ("GE39") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("CI206") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "LUNDI", "CI206", 3, "TD", "GE39") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "09:00", "LUNDI", "CI206");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "16:30", "MERCREDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "10:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("RO03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA100", 2, "Cours", "RO03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "16:30", "LUNDI", "FA100");
INSERT INTO uv (nom) VALUES ("RO03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA419") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA419", 2, "TD", "RO03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "10:15", "MERCREDI", "FA419");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "VENDREDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jo.colina@etu.utc.fr", "13:15", "VENDREDI", "FA506");
INSERT INTO etudiant VALUES ("irvin.gerbeaux@etu.utc.fr", "Gerbeaux", "Irvin", "GB");
INSERT INTO uv (nom) VALUES ("IC05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA204") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MARDI", "FA204", 2, "Cours", "IC05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "10:15", "MARDI", "FA204");
INSERT INTO uv (nom) VALUES ("IC05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA509", 2, "TD", "IC05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "14:15", "MARDI", "FA509");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA205") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA205", 1, "Cours", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "13:00", "MARDI", "FA205");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC114") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "JEUDI", "FC114", 2, "TD", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "14:15", "JEUDI", "FC114");
INSERT INTO uv (nom) VALUES ("MP02") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "VENDREDI", "FA202", 2, "Cours", "MP02") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "16:30", "VENDREDI", "FA202");
INSERT INTO uv (nom) VALUES ("MP02") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "VENDREDI", "FA509", 2, "TD", "MP02") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "14:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "16:30", "MERCREDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "08:00", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("RO04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA200", 2, "Cours", "RO04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "16:30", "MARDI", "FA200");
INSERT INTO uv (nom) VALUES ("RO04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA418") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA418", 2, "TD", "RO04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "08:00", "JEUDI", "FA418");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("irvin.gerbeaux@etu.utc.fr", "16:30", "LUNDI", "FA506");
INSERT INTO etudiant VALUES ("jérémy.coste@etu.utc.fr", "Coste", "Jérémy", "GB");
INSERT INTO uv (nom) VALUES ("LG53") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC203") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FC203", 2, "TD", "LG53") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "14:15", "MARDI", "FC203");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "10:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("SI24") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA419") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "MARDI", "FA419", 1, "Cours", "SI24") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "09:00", "MARDI", "FA419");
INSERT INTO uv (nom) VALUES ("SI24") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MARDI", "FA509", 2, "TD", "SI24") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "10:15", "MARDI", "FA509");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "16:30", "LUNDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "10:15", "LUNDI", "J210A");
INSERT INTO uv (nom) VALUES ("SY26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "LUNDI", "FA202", 2, "Cours", "SY26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "08:00", "LUNDI", "FA202");
INSERT INTO uv (nom) VALUES ("SY26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB215") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FB215", 2, "TD", "SY26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "16:30", "MARDI", "FB215");
INSERT INTO uv (nom) VALUES ("SY26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB215") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "LUNDI", "FB215", 2, "TP", "SY26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("jérémy.coste@etu.utc.fr", "14:15", "LUNDI", "FB215");
INSERT INTO etudiant VALUES ("robin.trouve@etu.utc.fr", "Trouve", "Robin", "GM");
INSERT INTO uv (nom) VALUES ("EI05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA200", 1, "Cours", "EI05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "13:00", "MARDI", "FA200");
INSERT INTO uv (nom) VALUES ("EI05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA309") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA309", 2, "TD", "EI05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "14:15", "MARDI", "FA309");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA104", 2, "Cours", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "16:30", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA509", 3, "TD", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "16:30", "MERCREDI", "FA509");
INSERT INTO uv (nom) VALUES ("LG31") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA410") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA410", 2, "TD", "LG31") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "10:15", "LUNDI", "FA410");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "10:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("robin.trouve@etu.utc.fr", "16:30", "MARDI", "FA506");
INSERT INTO etudiant VALUES ("quentin.duchemin@etu.utc.fr", "Duchemin", "Quentin", "GM");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA104", 2, "Cours", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "16:30", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB113") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FB113", 3, "TD", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "16:30", "MARDI", "FB113");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "10:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("PH01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("12:30", "MERCREDI", "FA108", 1, "Cours", "PH01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "12:30", "MERCREDI", "FA108");
INSERT INTO uv (nom) VALUES ("PH01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA204") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA204", 2, "TD", "PH01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "10:15", "MERCREDI", "FA204");
INSERT INTO uv (nom) VALUES ("SC23") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA206") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA206", 1, "Cours", "SC23") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "13:00", "MARDI", "FA206");
INSERT INTO uv (nom) VALUES ("SC23") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA206") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA206", 2, "TD", "SC23") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "14:15", "MARDI", "FA206");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "VENDREDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "13:15", "VENDREDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.duchemin@etu.utc.fr", "10:15", "LUNDI", "J210A");
INSERT INTO etudiant VALUES ("aurélie.digeon@etu.utc.fr", "Digeon", "Aurélie", "GB");
INSERT INTO uv (nom) VALUES ("GE13") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA317", 1, "Cours", "GE13") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "13:00", "MARDI", "FA317");
INSERT INTO uv (nom) VALUES ("GE13") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA317", 2, "TD", "GE13") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "16:30", "MARDI", "FA317");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA104", 2, "Cours", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "16:30", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA509", 3, "TD", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "16:30", "MERCREDI", "FA509");
INSERT INTO uv (nom) VALUES ("LG53") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC203") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FC203", 2, "TD", "LG53") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "14:15", "MARDI", "FC203");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "08:00", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA317", 2, "Cours", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "08:00", "JEUDI", "FA317");
INSERT INTO uv (nom) VALUES ("NF26") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FB100", 2, "TD", "NF26") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "10:15", "VENDREDI", "FB100");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA201", 2, "Cours", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "10:15", "MERCREDI", "FA201");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB215") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "VENDREDI", "FB215", 2, "TD", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.digeon@etu.utc.fr", "14:15", "VENDREDI", "FB215");
INSERT INTO etudiant VALUES ("alexandre-guillaume.gilbert@etu.utc.fr", "Gilbert", "Alexandre-Guillaume", "GI");
INSERT INTO etudiant VALUES ("maxime.dilly@etu.utc.fr", "Dilly", "Maxime", "GB");
INSERT INTO uv (nom) VALUES ("HE01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "MARDI", "FA108", 1, "Cours", "HE01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "09:00", "MARDI", "FA108");
INSERT INTO uv (nom) VALUES ("HE01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA307") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA307", 2, "TD", "HE01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "14:15", "MARDI", "FA307");
INSERT INTO uv (nom) VALUES ("RO04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA200", 2, "Cours", "RO04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "16:30", "MARDI", "FA200");
INSERT INTO uv (nom) VALUES ("RO04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA418") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA418", 2, "TD", "RO04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "08:00", "JEUDI", "FA418");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "16:30", "LUNDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("maxime.dilly@etu.utc.fr", "10:15", "LUNDI", "J210A");
INSERT INTO etudiant VALUES ("antoine.rondelet@etu.utc.fr", "Rondelet", "Antoine", "GI");
INSERT INTO uv (nom) VALUES ("IC05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA204") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MARDI", "FA204", 2, "Cours", "IC05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "10:15", "MARDI", "FA204");
INSERT INTO uv (nom) VALUES ("IC05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA509", 2, "TD", "IC05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "16:30", "MARDI", "FA509");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA205") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA205", 1, "Cours", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "13:00", "MARDI", "FA205");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC114") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FC114", 2, "TD", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "10:15", "JEUDI", "FC114");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "16:30", "MERCREDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "08:00", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "16:30", "LUNDI", "FA506");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "JEUDI", "FA108", 3, "Cours", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "13:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("SR05") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("J210A") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "J210A", 3, "TD", "SR05") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("antoine.rondelet@etu.utc.fr", "10:15", "LUNDI", "J210A");
INSERT INTO etudiant VALUES ("aurélie.brun@etu.utc.fr", "Brun", "Aurélie", "GM");
INSERT INTO uv (nom) VALUES ("BI01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA200", 2, "Cours", "BI01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "16:30", "LUNDI", "FA200");
INSERT INTO uv (nom) VALUES ("BI01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MARDI", "FA516", 2, "TD", "BI01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "08:00", "MARDI", "FA516");
INSERT INTO uv (nom) VALUES ("BT06") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA317") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA317", 2, "Cours", "BT06") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "14:15", "MERCREDI", "FA317");
INSERT INTO uv (nom) VALUES ("BT06") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA418") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA418", 2, "TD", "BT06") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "16:30", "MERCREDI", "FA418");
INSERT INTO uv (nom) VALUES ("BT06") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RJ202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "RJ202", 4, "TP", "BT06") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "08:00", "VENDREDI", "RJ202");
INSERT INTO uv (nom) VALUES ("BT21") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "VENDREDI", "FA202", 2, "Cours", "BT21") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "14:15", "VENDREDI", "FA202");
INSERT INTO uv (nom) VALUES ("BT21") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA419") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "VENDREDI", "FA419", 2, "TD", "BT21") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "16:30", "VENDREDI", "FA419");
INSERT INTO uv (nom) VALUES ("BT21") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB116") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FB116", 4, "TP", "BT21") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "08:00", "VENDREDI", "FB116");
INSERT INTO uv (nom) VALUES ("CM15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA212") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA212", 2, "Cours", "CM15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "08:00", "JEUDI", "FA212");
INSERT INTO uv (nom) VALUES ("CM15") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA212") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA212", 2, "TD", "CM15") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "10:15", "JEUDI", "FA212");
INSERT INTO uv (nom) VALUES ("GE36") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "LUNDI", "FA108", 1, "Cours", "GE36") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "09:00", "LUNDI", "FA108");
INSERT INTO uv (nom) VALUES ("GE36") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA307") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA307", 2, "TD", "GE36") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "10:15", "LUNDI", "FA307");
INSERT INTO uv (nom) VALUES ("LB14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "LUNDI", "FA104", 1, "Cours", "LB14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "13:00", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("LB14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC114") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FC114", 2, "TD", "LB14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "08:00", "MERCREDI", "FC114");
INSERT INTO uv (nom) VALUES ("TS01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA104", 2, "Cours", "TS01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "14:15", "MARDI", "FA104");
INSERT INTO uv (nom) VALUES ("TS01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA406") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA406", 2, "TD", "TS01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("aurélie.brun@etu.utc.fr", "10:15", "MERCREDI", "FA406");
INSERT INTO etudiant VALUES ("rachid.khalef@etu.utc.fr", "Khalef", "Rachid", "GP");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA205") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA205", 1, "Cours", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "13:00", "MARDI", "FA205");
INSERT INTO uv (nom) VALUES ("LC14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC114") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FC114", 2, "TD", "LC14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "10:15", "JEUDI", "FC114");
INSERT INTO uv (nom) VALUES ("LG60") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA414") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "LUNDI", "FA414", 2, "TD", "LG60") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "08:00", "LUNDI", "FA414");
INSERT INTO uv (nom) VALUES ("MP02") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA202") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "VENDREDI", "FA202", 2, "Cours", "MP02") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "16:30", "VENDREDI", "FA202");
INSERT INTO uv (nom) VALUES ("MP02") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "VENDREDI", "FA509", 2, "TD", "MP02") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "14:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("NF28") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA200", 2, "Cours", "NF28") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "10:15", "LUNDI", "FA200");
INSERT INTO uv (nom) VALUES ("NF28") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO227") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "LUNDI", "RO227", 3, "TD", "NF28") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "13:00", "LUNDI", "RO227");
INSERT INTO uv (nom) VALUES ("RO04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA200", 2, "Cours", "RO04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "16:30", "MARDI", "FA200");
INSERT INTO uv (nom) VALUES ("RO04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA418") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FA418", 2, "TD", "RO04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "08:00", "JEUDI", "FA418");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "16:30", "LUNDI", "FA506");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA201") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA201", 2, "Cours", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "10:15", "MERCREDI", "FA201");
INSERT INTO uv (nom) VALUES ("SY09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA509", 2, "TD", "SY09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("rachid.khalef@etu.utc.fr", "08:00", "MERCREDI", "FA509");
INSERT INTO etudiant VALUES ("oscar.odic@etu.utc.fr", "Odic", "Oscar", "GP");
INSERT INTO uv (nom) VALUES ("AH03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA304") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "VENDREDI", "FA304", 4, "TD", "AH03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "14:15", "VENDREDI", "FA304");
INSERT INTO uv (nom) VALUES ("AH14") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA304") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA304", 2, "TD", "AH14") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "16:30", "MERCREDI", "FA304");
INSERT INTO uv (nom) VALUES ("AH17") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA304") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "SAMEDI", "FA304", 4, "TD", "AH17") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "08:00", "SAMEDI", "FA304");
INSERT INTO uv (nom) VALUES ("AI09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA505") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "JEUDI", "FA505", 3, "TD", "AI09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "14:15", "JEUDI", "FA505");
INSERT INTO uv (nom) VALUES ("AI09") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA505") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "VENDREDI", "FA505", 3, "TD", "AI09") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "08:00", "VENDREDI", "FA505");
INSERT INTO uv (nom) VALUES ("AI16") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "JEUDI", "FB104", 4, "TD", "AI16") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "08:00", "JEUDI", "FB104");
INSERT INTO uv (nom) VALUES ("AI18") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA505") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "LUNDI", "FA505", 4, "TD", "AI18") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "14:15", "LUNDI", "FA505");
INSERT INTO uv (nom) VALUES ("AI18") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA505") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MARDI", "FA505", 2, "TD", "AI18") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "08:00", "MARDI", "FA505");
INSERT INTO uv (nom) VALUES ("AI19") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MARDI", "FB100", 2, "TD", "AI19") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "10:15", "MARDI", "FB100");
INSERT INTO uv (nom) VALUES ("AI19") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FB100") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FB100", 2, "TD", "AI19") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("oscar.odic@etu.utc.fr", "08:00", "MERCREDI", "FB100");
INSERT INTO etudiant VALUES ("adrien.aron@etu.utc.fr", "Aron", "Adrien", "GSU");
INSERT INTO uv (nom) VALUES ("FQ01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("CT120") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "SAMEDI", "CT120", 3, "Cours", "FQ01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "09:00", "SAMEDI", "CT120");
INSERT INTO uv (nom) VALUES ("FQ01") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA108", 2, "TD", "FQ01") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "10:15", "VENDREDI", "FA108");
INSERT INTO uv (nom) VALUES ("GE36") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("09:00", "LUNDI", "FA108", 1, "Cours", "GE36") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "09:00", "LUNDI", "FA108");
INSERT INTO uv (nom) VALUES ("GE36") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA307") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA307", 2, "TD", "GE36") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "10:15", "LUNDI", "FA307");
INSERT INTO uv (nom) VALUES ("GE37") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RB110") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "LUNDI", "RB110", 2, "Cours", "GE37") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "14:15", "LUNDI", "RB110");
INSERT INTO uv (nom) VALUES ("GE37") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO128") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "RO128", 3, "TD", "GE37") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "16:30", "LUNDI", "RO128");
INSERT INTO uv (nom) VALUES ("MQ03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA108", 2, "Cours", "MQ03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "10:15", "JEUDI", "FA108");
INSERT INTO uv (nom) VALUES ("MQ03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA314") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MARDI", "FA314", 2, "TD", "MQ03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "16:30", "MARDI", "FA314");
INSERT INTO uv (nom) VALUES ("MQ03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RJ103") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:30", "MERCREDI", "RJ103", 4, "TP", "MQ03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "14:30", "MERCREDI", "RJ103");
INSERT INTO uv (nom) VALUES ("PH03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA108") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FA108", 2, "Cours", "PH03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "14:15", "MARDI", "FA108");
INSERT INTO uv (nom) VALUES ("PH03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA307") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "MARDI", "FA307", 1, "TD", "PH03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "13:00", "MARDI", "FA307");
INSERT INTO uv (nom) VALUES ("SY04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "MERCREDI", "FA104", 2, "Cours", "SY04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "10:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SY04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA309") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MARDI", "FA309", 2, "TD", "SY04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "08:00", "MARDI", "FA309");
INSERT INTO uv (nom) VALUES ("SY04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RJ219") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:30", "JEUDI", "RJ219", 4, "TP", "SY04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("adrien.aron@etu.utc.fr", "14:30", "JEUDI", "RJ219");
INSERT INTO etudiant VALUES ("quentin.drualt-aubin@etu.utc.fr", "Drualt-Aubin", "Quentin", "GP");
INSERT INTO uv (nom) VALUES ("EI04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO230") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "LUNDI", "RO230", 1, "Cours", "EI04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "13:00", "LUNDI", "RO230");
INSERT INTO uv (nom) VALUES ("EI04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO128") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "LUNDI", "RO128", 2, "TD", "EI04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "14:15", "LUNDI", "RO128");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "LUNDI", "FA104", 2, "Cours", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "16:30", "LUNDI", "FA104");
INSERT INTO uv (nom) VALUES ("IA04") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("16:30", "MERCREDI", "FA509", 3, "TD", "IA04") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "16:30", "MERCREDI", "FA509");
INSERT INTO uv (nom) VALUES ("LA23") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FC111") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MARDI", "FC111", 2, "TD", "LA23") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "14:15", "MARDI", "FC111");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA106") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("08:00", "MERCREDI", "FA106", 2, "Cours", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "08:00", "MERCREDI", "FA106");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA516") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "JEUDI", "FA516", 2, "TD", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "10:15", "JEUDI", "FA516");
INSERT INTO uv (nom) VALUES ("NF11") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA509") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "VENDREDI", "FA509", 2, "TP", "NF11") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "10:15", "VENDREDI", "FA509");
INSERT INTO uv (nom) VALUES ("NF28") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA200") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("10:15", "LUNDI", "FA200", 2, "Cours", "NF28") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "10:15", "LUNDI", "FA200");
INSERT INTO uv (nom) VALUES ("NF28") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("RO227") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:00", "JEUDI", "RO227", 3, "TD", "NF28") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "13:00", "JEUDI", "RO227");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA104") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("14:15", "MERCREDI", "FA104", 2, "Cours", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "14:15", "MERCREDI", "FA104");
INSERT INTO uv (nom) VALUES ("SR03") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO salle (nom) VALUES ("FA506") ON DUPLICATE KEY UPDATE nom=nom;
INSERT INTO edt (heure_debut,jour,salle,duree,type,uv) VALUES ("13:15", "VENDREDI", "FA506", 3, "TD", "SR03") ON DUPLICATE KEY UPDATE heure_debut=heure_debut;
INSERT INTO inscription VALUES ("quentin.drualt-aubin@etu.utc.fr", "13:15", "VENDREDI", "FA506");

