drop schema if exists SR03Projet;
create schema SR03Projet;
use SR03Projet;
create table Branche (abreviation varchar(50) not null, nom varchar(50), primary key (abreviation));
create table Edt (heure_debut varchar(50) not null, jour varchar(50) not null, salle varchar(50) not null, duree integer not null, type varchar(50), uv varchar(50), primary key (heure_debut, jour, salle));
create table Etudiant (mail varchar(50) not null, login varchar(50) not null, nom varchar(50), prenom varchar(50), branche varchar(50), primary key (mail));
create table Inscription (mail varchar(50) not null, heure_debut varchar(50) not null, jour varchar(50) not null, salle varchar(50) not null);
create table Jour (nom varchar(50) not null, primary key (nom));
create table Salle (nom varchar(50) not null, primary key (nom));
create table Uv (nom varchar(50) not null, description varchar(50), primary key (nom));
alter table Edt add constraint FKhgvkdqcr65ijy50uavitpibn9 foreign key (jour) references Jour (nom);
alter table Edt add constraint FK9siat9vv9gjlunsrwd4wcc73h foreign key (salle) references Salle (nom);
alter table Edt add constraint FK2976ef9ow5g5ttxwa08qgo6v0 foreign key (uv) references Uv (nom);
alter table Etudiant add constraint FKpitbe9bvy3ijxqi3vi6ltjs1e foreign key (branche) references Branche (abreviation);
alter table Inscription add constraint FKo74epmx5attuowjqycn37ahqa foreign key (heure_debut, jour, salle) references Edt (heure_debut, jour, salle);
alter table Inscription add constraint FKg7jrpmuhksknj4loc94lej0fi foreign key (mail) references Etudiant (mail);
INSERT into Branche
VALUES('GI', 'Génie Informatique'),('GM', 'Génie Mécanique'),('GB', 'Génie Biologique'),('GSU', 'Génie des Systèmes Urbains'),('TC', 'Tronc Commun'),('GP','Génie des Procédés');
INSERT INTO Jour VALUES ("LUNDI"), ("MARDI"), ("MERCREDI"), ("JEUDI"), ("VENDREDI"), ("SAMEDI");
create table Compte (pseudo varchar(50) not null, password varchar(500) not null, primary key(pseudo));
insert into Compte values ('admin', 'd033e22ae348aeb5660fc2140aec35850c4da997');
commit;