package model;
// Generated 3 mai 2017 18:45:16 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Edt generated by hbm2java
 */
@Entity
public class Edt implements java.io.Serializable {

	private EdtId id;
	private Jour jour;
	private Salle salle;
	private Uv uv;
	private int duree;
	private String type;
	
	public Edt() {
	}

	public Edt(EdtId id, Jour jour, Salle salle, int duree) {
		this.id = id;
		this.jour = jour;
		this.salle = salle;
		this.duree = duree;
	}

	public Edt(EdtId id, Jour jour, Salle salle, Uv uv, int duree, String type) {
		this.id = id;
		this.jour = jour;
		this.salle = salle;
		this.uv = uv;
		this.duree = duree;
		this.type = type;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "heureDebut", column = @Column(name = "heure_debut", nullable = false, length = 10)),
			@AttributeOverride(name = "jour", column = @Column(name = "jour", nullable = false)),
			@AttributeOverride(name = "salle", column = @Column(name = "salle", nullable = false)) })
	public EdtId getId() {
		return this.id;
	}

	public void setId(EdtId id) {
		this.id = id;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "jour", nullable = false, insertable = false, updatable = false)
	public Jour getJour() {
		return this.jour;
	}

	public void setJour(Jour jour) {
		this.jour = jour;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "salle", nullable = false, insertable = false, updatable = false)
	public Salle getSalle() {
		return this.salle;
	}

	public void setSalle(Salle salle) {
		this.salle = salle;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "uv")
	public Uv getUv() {
		return this.uv;
	}

	public void setUv(Uv uv) {
		this.uv = uv;
	}

	@Column(name = "duree", nullable = false)
	public int getDuree() {
		return this.duree;
	}

	public void setDuree(int duree) {
		this.duree = duree;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
}
