package model;
// Generated 3 mai 2017 18:45:16 by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EdtId generated by hbm2java
 */
@Embeddable
public class EdtId implements java.io.Serializable {

	private String heureDebut;
	private String jour;
	private String salle;

	public EdtId() {
	}

	public EdtId(String heureDebut, String jour, String salle) {
		this.heureDebut = heureDebut;
		this.jour = jour;
		this.salle = salle;
	}

	@Column(name = "heure_debut", nullable = false, length = 10)
	public String getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(String heureDebut) {
		this.heureDebut = heureDebut;
	}

	@Column(name = "jour", nullable = false)
	public String getJour() {
		return this.jour;
	}

	public void setJour(String jour) {
		this.jour = jour;
	}

	@Column(name = "salle", nullable = false)
	public String getSalle() {
		return this.salle;
	}

	public void setSalle(String salle) {
		this.salle = salle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EdtId))
			return false;
		EdtId castOther = (EdtId) other;

		return ((this.getHeureDebut() == castOther.getHeureDebut()) || (this.getHeureDebut() != null
				&& castOther.getHeureDebut() != null && this.getHeureDebut().equals(castOther.getHeureDebut())))
				&& ((this.getJour() == castOther.getJour()) || (this.getJour() != null && castOther.getJour() != null
						&& this.getJour().equals(castOther.getJour())))
				&& ((this.getSalle() == castOther.getSalle()) || (this.getSalle() != null
						&& castOther.getSalle() != null && this.getSalle().equals(castOther.getSalle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHeureDebut() == null ? 0 : this.getHeureDebut().hashCode());
		result = 37 * result + (getJour() == null ? 0 : this.getJour().hashCode());
		result = 37 * result + (getSalle() == null ? 0 : this.getSalle().hashCode());
		return result;
	}

}
