package model;
// Generated 3 mai 2017 18:45:16 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
public class Etudiant implements java.io.Serializable {

	private String mail;
	private Branche branche;
	private String nom;
	private String prenom;

	public Etudiant() {
	}

	public Etudiant(String mail) {
		this.mail = mail;
	}

	public Etudiant(String mail, Branche branche, String nom, String prenom) {
		super();
		this.mail = mail;
		this.branche = branche;
		this.nom = nom;
		this.prenom = prenom;
	}

	@Id

	@Column(name = "mail", unique = true, nullable = false)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "branche")
	public Branche getBranche() {
		return this.branche;
	}

	public void setBranche(Branche branche) {
		this.branche = branche;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
