package model;
// Generated 3 mai 2017 18:45:16 by Hibernate Tools 4.3.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Inscription generated by hbm2java
 */
@Entity
public class Inscription implements java.io.Serializable {

	private InscriptionId id;
	private Edt edt;
	private Etudiant etudiant;

	public Inscription() {
	}

	public Inscription(InscriptionId id, Edt edt, Etudiant etudiant) {
		this.id = id;
		this.edt = edt;
		this.etudiant = etudiant;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mail", column = @Column(name = "mail", nullable = false)),
			@AttributeOverride(name = "heureDebut", column = @Column(name = "heure_debut", nullable = false, length = 19)),
			@AttributeOverride(name = "jour", column = @Column(name = "jour", nullable = false)),
			@AttributeOverride(name = "salle", column = @Column(name = "salle", nullable = false)) })
	public InscriptionId getId() {
		return this.id;
	}

	public void setId(InscriptionId id) {
		this.id = id;
	}

	@OneToOne(optional = false)
	@JoinColumns({
			@JoinColumn(name = "heure_debut", referencedColumnName = "heure_debut", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "jour", referencedColumnName = "jour", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "salle", referencedColumnName = "salle", nullable = false, insertable = false, updatable = false) })
	public Edt getEdt() {
		return this.edt;
	}

	public void setEdt(Edt edt) {
		this.edt = edt;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "mail", nullable = false, insertable = false, updatable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

}
