package model;
// Generated 3 mai 2017 18:45:16 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jour generated by hbm2java
 */
@Entity
public class Jour implements java.io.Serializable {

	private String nom;

	public Jour() {
	}

	public Jour(String nom) {
		this.nom = nom;
	}

	public Jour(String nom, Set<Edt> edts) {
		this.nom = nom;
	}

	@Id

	@Column(name = "nom", unique = true, nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
}
