package model;
// Generated 3 mai 2017 18:45:16 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Uv generated by hbm2java
 */
@Entity
public class Uv implements java.io.Serializable {

	private String nom;
	private String description;

	public Uv() {
	}

	public Uv(String nom) {
		this.nom = nom;
	}

	public Uv(String nom, String description, Set<Edt> edts) {
		this.nom = nom;
		this.description = description;
	}

	@Id

	@Column(name = "nom", unique = true, nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
